# Generated by Django 4.2.23 on 2025-09-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymouscomment',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='comments_audio/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
