# Generated by Django 4.2.23 on 2025-09-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_anonymouscomment_audio_photo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymouscomment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
